### ISSUE TITLE
Work only on fortinite?

### ISSUE THREAD

**Issue by Allmight0000** [MistyAI/MistyFN#6]
?

**Comment by dewPrzemuS** [comment]
I haven't tried it, there is a chance that it works in other games as well, because as far as I know the model used in MistyFN was created for detecting humanoid characters, not specifically for Fortnite characters.

**Comment by Allmight0000** [comment]
How do I change the activation mode for the mouse aim button?

**Comment by dewPrzemuS** [comment]
Currently it is not possible, such a function is already on the to-do list and waits for implementation.
